### ISSUE TITLE
关于固件的获取

### ISSUE THREAD

**Issue by add1314** [liyansong2018/firmware-analysis-plus#1]
请问作者，您用来模拟的固件在哪里可以找到，我现在除了官方的实例，没有找到其他合适的

**Comment by liyansong2018** [comment]
在各个路由器厂商的相关网站上都可以找到。我们使用的示例固件来自[https://www.netgear.com/support/product/]( https://www.netgear.com/support/product/)，对于非通用的固件，事实上可以自己定制 qemu 来模拟定制化程度较高的固件。
