### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by issacgompertz** [liyansong2018/firmware-analysis-plus#12]

**Comment by issacgompertz** [comment]
FAP 暂时还不支持mips小端，因此有这个错误

**Comment by liyansong2018** [comment]
32位mips小端是支持的，kernel panic 原因很多，可以提供一下固件版本么，应该跟你仿真的具体固件有关系

**Comment by issacgompertz** [comment]
> 32位mips小端是支持的，kernel panic 原因很多，可以提供一下固件版本么，应该跟你仿真的具体固件有关系

**Comment by issacgompertz** [comment]
> 32位mips小端是支持的，kernel panic 原因很多，可以提供一下固件版本么，应该跟你仿真的具体固件有关系

你邮箱是多少啊，详聊

**Comment by liyansong2018** [comment]
> > 32位mips小端是支持的，kernel panic 原因很多，可以提供一下固件版本么，应该跟你仿真的具体固件有关系
> 
> 你邮箱是多少啊，详聊

微软的邮箱：liyansong2012
