### ISSUE TITLE
network

### ISSUE THREAD

**Issue by zhulink** [liyansong2018/firmware-analysis-plus#13]
用fat.py模拟环境的时候，运行过程中，给出的网络 接口为空的[+] Network interfaces : []，是在Ubuntu14.04的虚拟机下运行的

**Comment by liyansong2018** [comment]
Linux发行版版本太老。
由于受到binwalk和firmadyne的影响，本项目最新版不支持Ubuntu中的某些版本，项目已经注明了支持的Linux发行版，请参见主页上的项目对应表。最新版的fap对Kali 2020.04兼容性最好。实在是想安装在较老的Ubuntu发行版上，可以使用fapv0.1。

**Comment by zhulink** [comment]
好的，感谢
