### ISSUE TITLE
关于建立网络报错

### ISSUE THREAD

**Issue by Yanyouke** [liyansong2018/firmware-analysis-plus#15]
![image](https://user-images.githubusercontent.com/41262396/119074390-869c2800-ba21-11eb-84b7-f5970c2ce54d.png)

**Comment by liyansong2018** [comment]
也许你可以看看 issue  #11，从你截图的上半部分看上去，原因是一样的。

**Comment by Yanyouke** [comment]
好的，谢谢老哥，麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyansong2018/firmware-analysis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liyansong2018/firmware-analysis-plus] 关于建立网络报错 (#15)





 
也许你可以看看 issue  #11，从你截图的上半部分看上去，原因是一样的。

**Comment by Yanyouke** [comment]
师傅，我刚才那台是ubuntu18.04，运行后依然为那个错误，我猜测是FAP内执行./setup.sh报错所致，以下为图




这个地方我找了半天不知道怎么解决了。之后我又创建了个kali2020.04的版本，照着流程走了一遍没有问题，但是最后卡在了解析固件，很久没有动了就，以下为图

师傅您刚才说到最好安装您的binwalk版本，但是我在安装完后执行binwalk好像是原有的版本，感觉是不是这个原因啊，不知道怎么办了现在，希望得到回应，谢谢师傅




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyansong2018/firmware-analysis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liyansong2018/firmware-analysis-plus] 关于建立网络报错 (#15)





 
也许你可以看看 issue  #11，从你截图的上半部分看上去，原因是一样的。

**Comment by liyansong2018** [comment]
没有看到你的截图。所以无法判断具体原因。不用着急，这个项目很多人实践过，按照流程走是没有问题的。

Kali自带binwalk正常使用是没有问题的，但是如果使用其提供的python接口，是存在问题的。所以需要源码编译binwalk。

**Comment by Yanyouke** [comment]
师傅方便留个联系方式吗，我再多试几个环境，确实时间有点紧，近期一直在做些研究


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyansong2018/firmware-analysis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liyansong2018/firmware-analysis-plus] 关于建立网络报错 (#15)





 
没有看到你的截图。所以无法判断具体原因。不用着急，这个项目很多人实践过，按照流程走是没有问题的。
 
Kali自带binwalk正常使用是没有问题的，但是如果使用其提供的python接口，是存在问题的。所以需要源码编译binwalk。
