### ISSUE TITLE
Binwalk安装失败

### ISSUE THREAD

**Issue by Brubbish** [liyansong2018/firmware-analysis-plus#18]
Kali 2021

![image](https://user-images.githubusercontent.com/29673689/123419409-c4760880-d5ec-11eb-9587-324692904574.png)

麻烦老哥了

**Comment by liyansong2018** [comment]
光从这个截图还看不出来，你可以贴更多的日志，直接打印出来而不是截图。你用的是原版的binwalk还是修改后的

**Comment by liyansong2018** [comment]
鉴于很多人编译`binwalk`都会出问题，当前正在计划：

无须编译binwalk，直接使用解压后的文件系统。代码正在修改，随后会更新。
