### ISSUE TITLE
登录命令行shell的问题

### ISSUE THREAD

**Issue by seanachao** [liyansong2018/firmware-analysis-plus#30]
在使用d-link DIR-846W进行模拟的过程中，固件仿真运行后，命令行终端显示  rtkmips login:，使用root/password尝试登录，终端反馈login incorrect ,是否还有其他密码？

**Comment by liyansong2018** [comment]
这个路由器没有实际测试过，如果你在网上没有查到相关密码，建议直接binwalk解压固件
方法一：打开 `/etc/passwd` 文件，删除密码，默认无密码，或者修改为自己的密码
```shell
# root:x:0:0:root:/root:/bin/bash
root::0:0:root:/root:/bin/bash
```
方法二：打开 `/etc/shadow`，使用 `openssl` 计算新密码，填充该文件
```shell
openssl passwd -1 -salt 'abcdefg' '123456'
```
重新将文件系统打包，或者就简单压缩一下，用 fap 重新模拟即可。

**Comment by seanachao** [comment]
两种方式都很可行，感谢师傅
