### ISSUE TITLE
一直卡在Pulling fs layer

### ISSUE THREAD

**Issue by HolyTruth** [liyansong2018/firmware-analysis-plus#49]
![image](https://user-images.githubusercontent.com/22108738/222450169-bb2133e0-5314-42b0-994c-403b74771c60.png)
卡在这里很久了，尝试过重新pull，也卡在这

**Comment by liyansong2018** [comment]
docker默认使用官方镜像地址，国内由于网络限制的因素，下载速度较慢。建议更换docker国内的镜像源，或者使用科学上网。

**Comment by liyansong2018** [comment]
已不推荐使用 docker，因为 docker 更新的缘故，导致 fap 在 docker 中运行出错。建议直接使用打包好的 [vmware镜像](https://pan.baidu.com/s/1eVNxoLKlqAQHcrSMfI7tQw?pwd=jpy4)。
