### ISSUE TITLE
before (last 100 chars): b'pid 3892000 (timeout)\r\nInferring network...\r\n/usr/bin/env: \xe2\x80\x98python\xe2\x80\x99: No such file or directory\r\n

### ISSUE THREAD

**Issue by jplopezy** [liyansong2018/firmware-analysis-plus#51]
Hi,

Can anyone help me understand why I'm getting this error: '/usr/bin/env: ‘python’: No such file or directory' when I try to run './fap.py testcases/iot_dir880l_110b01.bin'? The last 100 characters before the error message indicate a 'pid 3892000 (timeout)' and 'Inferring network...' message. Any insight would be appreciated.

FULL LOG:

[+] Firmware: iot_dir880l_110b01.bin
[+] Extracting the firmware...
[+] Image ID: 1
[+] Identifying architecture...
[+] Architecture: armel
[+] Building QEMU disk image...
[+] Setting up the network connection, please standby...
Traceback (most recent call last):
  File "/home/test/firmware-analysis-plus/./fap.py", line 210, in <module>
    main()
  File "/home/test/firmware-analysis-plus/./fap.py", line 205, in main
    infer_network(arch, image_id, args.time, qemu_dir, host)
  File "/home/test/firmware-analysis-plus/./fap.py", line 136, in infer_network
    child.expect_exact("Interfaces:", timeout=None)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f3e50837c10>
command: /home/test/firmadyne/scripts/inferNetwork.sh
args: ['/home/test/firmadyne/scripts/inferNetwork.sh', '1', 'armel', '60']
buffer (last 100 chars): b''
before (last 100 chars): b'pid 3892000 (timeout)\r\nInferring network...\r\n/usr/bin/env: \xe2\x80\x98python\xe2\x80\x99: No such file or directory\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 3891999
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: b'Interfaces:'

**Comment by liyansong2018** [comment]
Ubuntu 20.04
