### ISSUE TITLE
无Network interfaces

### ISSUE THREAD

**Issue by Wang1997** [liyansong2018/firmware-analysis-plus#55]
虚拟机环境：ubuntu 18.04
我在本地模拟跑固件出现Network interfaces为空的问题，使用testcases中的iot_dir880l_110b01.bin正常
乌班图本地模拟跑的固件链接文件如下
https://gitee.com/xj96/router-firmware/raw/master/linksys_wrt54gv2_fw4007.zip
切换使用docker，跑testcases中的iot_dir880l_110b01.bin，发现也出现了同样的问题，不知是否docker版本过高
![1705753103(1)](https://github.com/liyansong2018/firmware-analysis-plus/assets/18186818/774dd243-5617-4f5e-9b38-5f8d1f2649dd)

**Comment by AAA-Fei** [comment]
您好，问题解决了吗？

**Comment by liyansong2018** [comment]
网络为空的原因有很多，可以参考历史已关闭的issue，如 #47  #20
- `firmadyne/scratch/num/` 路径下有详细日志

**Comment by liyansong2018** [comment]
由于docker更新，当前确实存在此问题。推荐使用 Ubuntu20.04，直接使用 fap。
