### ISSUE TITLE
Docker端口转发问题

### ISSUE THREAD

**Issue by ImTopz** [liyansong2018/firmware-analysis-plus#57]
我的宿主机ip addr 是 192.168.31.52, 我的docker启动命令如下：
```
sudo docker run -it --privileged -p 8090:80 --name fap liyansong2022/fap-docker:2.3.1 /bin/bash
```
在docker容器中 vim /etc/rinetd.conf, 将0.0.0.0 80 转发到 192.168.31.52 8090，之后通过pkill与rinetd -c /etc/rinetd.conf， 再执行fap模拟testcases中的iot固件，在宿主机的8090端口无法访问到固件的web服务。 宿主机与docker容器通信没问题

**Comment by liyansong2018** [comment]
由于docker更新，当前确实存在此问题。推荐使用Ubuntu20.04，直接使用fap。
