### ISSUE TITLE
宿主机无妨访问

### ISSUE THREAD

**Issue by dctorwho** [liyansong2018/firmware-analysis-plus#58]
![微信截图_20240524122250](https://github.com/liyansong2018/firmware-analysis-plus/assets/91296098/5874d630-ec58-46e0-9da8-15c8eb37261f)
![微信截图_20240524122300](https://github.com/liyansong2018/firmware-analysis-plus/assets/91296098/95462100-6ed2-43b0-b3aa-e79340bfc40f)
![微信截图_20240524122320](https://github.com/liyansong2018/firmware-analysis-plus/assets/91296098/a9b0de20-880e-469f-821a-3e3bf8db8363)
这是ifconfig的结果：
![微信截图_20240524122519](https://github.com/liyansong2018/firmware-analysis-plus/assets/91296098/43aad514-ee0e-4731-a3e5-4a17ad015f23)
这是ip route的结果：
![微信截图_20240524122605](https://github.com/liyansong2018/firmware-analysis-plus/assets/91296098/94ba9415-9a6a-4e1b-bf8c-4847eb107bb9)
以及我尝试桥接模式，还是ping不通

**Comment by liyansong2018** [comment]
由于docker更新，当前确实存在此问题。推荐使用Ubuntu20.04，直接使用fap。

**Comment by liyansong2018** [comment]
可以直接使用打包好的 [vmware镜像](https://pan.baidu.com/s/1eVNxoLKlqAQHcrSMfI7tQw?pwd=jpy4)。
