### ISSUE TITLE
请问楼主这个binwalk和FAP项目是同级目录码？还是FAP项目在binwalk文件夹里？

### ISSUE THREAD

**Issue by 1604010326** [liyansong2018/firmware-analysis-plus#7]

**Comment by 1604010326** [comment]
楼主，我已经成功安上了，到了登录界面，可是用户名密码试了root/password进不去啊？用户名和密码这里应该是啥呢

**Comment by liyansong2018** [comment]
binwalk 是独立的，随便放哪安装都可以；这个固件有 bug，这个用户名和密码（Web 的登录密码是：`admin/password`，shell 的登录密码是 `root/password`）不是每次都能登录成功的

可以换一个固件（`DIR-601_REVB_FIRMWARE_2.01.BIN`、`DIR890A1_FW103b07.bin`）；

**Comment by 1604010326** [comment]
> DIR890A1_FW103b07.bin

谢谢，提前祝楼主新年快乐！

**Comment by liyansong2018** [comment]
新年快乐！

**Comment by liyansong2018** [comment]
新年快乐！
