### ISSUE TITLE
RTNETLINK answers: Network is Down & Error: Nexthop has invalid gateway.

### ISSUE THREAD

**Issue by tomfyele** [liyansong2018/firmware-analysis-plus#9]
When I run/ fat.py Script, the following error occurred

```shell
Initializing VLAN...
RTNETLINK answers: Network is down
Bringing up TAP device...
RTNETLINK answers: Network is down
Adding route to 192.168.0.1...
Error: Nexthop has invalid gateway.

```

**Comment by liyansong2018** [comment]
There was a network configuration bug in early firmadyne, which caused some network problems when running some programs. This problem was later fixed, but the relevant patch was not included. I've modified the code.
